### ISSUE TITLE
User specific directory root

### ISSUE THREAD

**Issue by barslmn** [vahaah/django-sftp#110]
- Django SFTP Server version: django-sftp==0.2.1
- Django version: 2.2.9
- Python version: 3.8.0
- Operating System: Ubuntu 18.04

### Description
Hey, 
Thanks a lot for great library. Does home_directory field in the user and group models work? Because when I connect to the server filezilla just lists the whole media root.

**Comment by vahaah** [comment]
Hi,

Thank you for your issue. I've fixed it. You need to set `home_directory` from the root eg. `/var/www/project/media/group_dir`

**Comment by barslmn** [comment]
Works as intended. Thanks a lot.
